Feature/124 custom segmented control
Fifis-Organization/Brocoli-se pull request #58
Opened 2021-11-16 14:47 UTC by nathaliacm

## 📝 Descrição

Adicionando segmented customizada na tela de lista de receitas.

## 🔢 Tarefa relacionada

124 - Segmented Control Customizada

## 📱 Screenshots e GIFs

<img width="485" alt="Screen Shot 2021-11-16 at 11 37 36" src="https://user-images.githubusercontent.com/50965665/142007090-f6d1d2ad-afbb-4f6c-8247-fafccff93ca9.png">

## ☑️ Tipo de mudança

- [x] ✅ Feature
- [ ] 🦟 BugFix
- [ ] 🚨 Hotfix
- [ ] 🚀 Release

## 🚨 Checklist 

- [x] Meu código compila normalmente
- [ ] Não existem warnings no lint
- [ ] Testes unitários

🖤 Obrigado! Você é lindo(a).PULL_REQUEST_TEMPLATE.md

2021-11-16 14:51 UTC, Prouj approved these changes

2021-11-16 14:52 UTC, ltuchoa requested changes

2021-11-16 14:52 UTC, ltuchoa commented on BrocoliSe/BrocoliSe/View/Components/CustomSegmentedControl.swift
> +        self.setDividerImage(UIImage(), forLeftSegmentState: .normal, rightSegmentState: .normal, barMetrics: .default)
podia colocar dentro do configure

2021-11-16 14:52 UTC, ltuchoa commented on BrocoliSe/BrocoliSe/View/Components/CustomSegmentedControl.swift
> +        leading.isActive = true
trocar pelo NSLayoutConstraints.activate já que é o padrão utilizado

2021-11-16 14:52 UTC, ltuchoa commented on BrocoliSe/BrocoliSe/View/Components/CustomSegmentedControl.swift
> +        leading.isActive = true
mesma coisa

2021-11-17 02:51 UTC, ltuchoa approved these changes

2021-11-17 11:19 UTC, merged